name: Common Folder Change Trigger

on:
  push:
    paths:
      - 'common/**'  # Triggers the workflow when changes occur in the 'common' folder
    branches:
      - master

jobs:
  trigger-lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Dispatch Trigger for Lambda Workflows
        run: |
          # Trigger lambda workflows
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GIT_PAT }}" \
            https://api.github.com/repos/himanshi0278/testing-workflow/dispatches \
            -d '{"event_type": "trigger-workflow"}'
