name: Common Folder Change Trigger

on:
  push:
    paths:
      - 'src/common/**'  # This ensures the workflow runs when any file in the common folder is modified

jobs:
  trigger-lambdas:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Trigger Lambda Workflow
      - name: Dispatch Trigger for Lambda Workflow
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.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 }}" \
            https://api.github.com/repos/himanshi0278/testing-workflow/dispatches \
            -d "{\"event_type\": \"trigger-workflow\"}"
