name: CI-CD - Common Changes

on:
  push:
    paths:
      - 'src/common/**'

jobs:
  dispatch_update:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Update Event
        uses: actions/github-script@v6
        with:
          script: |
            github.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'trigger-workflow',
              client_payload: { 
                // Optional: You can include data here to send to other workflows 
                //  e.g., 'branch': context.ref
                //  e.g., 'commit_message': context.payload.head_commit.message
              }
            })
