name: CI-CD - Common Changes

on:
  push:
    paths:
      - 'src/common/**'

jobs:
  dispatch_update:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Update Event for All Workflows
        uses: actions/github-script@v6
        with:
          script: |
            const workflows = [
              'createTransaction',
              'ctobFailedResponseFormatter',
              'ctobformatRequest',
              'ctobProcess',
              'ctobProcessCallback',
              'ctobRequest',
              'ctobSuccessResponseFormatter',
              'frontCtobRequest',
              'getToken',
              'getTransactionStatus',
              'router',
              'transactionRequestValidator',
              'updateTransaction'
            ];
            for (const workflow of workflows) {
              await github.repos.createDispatchEvent({
                owner: 'himanshi0278',
                repo: 'testing-workflow',
                event_type: 'trigger-workflow',
                client_payload: { workflow_name: workflow }
              });
            }
