name: CI-CD - frontCtobRequest

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Code Checkout
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Build Lambda Function Module (Skipping Tests)
      - name: Build frontCtobRequest Module
        run: mvn clean install -DskipTests=true -pl src/services/pg/frontCtobRequest -am

      # Step 4: Package Lambda Deployment
      - name: Package Lambda
        run: |
          JAR_PATH="src/services/pg/frontCtobRequest/target/frontCtobRequest-1.0-SNAPSHOT.jar"
          ZIP_PATH="src/services/pg/frontCtobRequest/frontCtobRequest.zip"
          zip -j "$ZIP_PATH" "$JAR_PATH"

      # Step 5: Upload Lambda Artifact
      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontCtobRequest
          path: src/services/pg/frontCtobRequest/frontCtobRequest.zip


       # Step 6: Download Lambda Package Artifact
      - name: Download Lambda Package
        uses: actions/download-artifact@v3
        with:
          name: frontCtobRequest
