
name: CI-CD - airtelmoney-getToken

on:
  repository_dispatch:
    types: [trigger-workflow]
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout Code
      - name: Code Checkout
        uses: actions/checkout@v3

      # Step 2: Setup Java
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Build Lambda Function Module
      - name: Build airtelmoney-getToken Module
        run: mvn clean install -pl src/operator/airtelmoney/getToken -am

      # Step 4: Package Lambda Deployment
      - name: Package Lambda
        run: |
          JAR_PATH="src/operator/airtelmoney/getToken/target/airtelmoney-getToken-1.0-SNAPSHOT.jar"
          ZIP_PATH="src/operator/airtelmoney/getToken/airtelmoney-getToken.zip"
          zip -j "$ZIP_PATH" "$JAR_PATH"

      # Step 5: Upload Artifact
      - name: Upload Lambda Artifact
        uses: actions/upload-artifact@v3
        with:
          name: airtelmoney-getToken
          path: src/operator/airtelmoney/getToken/airtelmoney-getToken.zip
    # Step 6: Download Lambda Package Artifact
      - name: Download Lambda Package
        uses: actions/download-artifact@v3
        with:
          name: airtelmoney-getToken


